import './globals.css';
import type { Metadata } from 'next';
import { Space_Mono, EB_Garamond } from 'next/font/google';
import { NavBar } from 'components';

const spaceMono = Space_Mono({ subsets: ['latin'], weight: ['400', '700'] });
export const EBGaramond = EB_Garamond({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${spaceMono.className} bg-light`}>
        <div className='flex w-full overflow-hidden h-screen items-start justify-between'>
          <NavBar />
          {children}
        </div>
      </body>
    </html>
  );
}
