import './globals.css';
import type { Metadata } from 'next';
import { fontMain } from 'fonts';
import { NavBar } from 'components';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${fontMain.className} bg-light`}>
        <div className='flex w-full overflow-hidden h-screen items-start justify-between'>
          <NavBar />
          {children}
        </div>
      </body>
    </html>
  );
}
